[theme]
primaryColor = "#1C1C1E"
backgroundColor = "#F0EEE9"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1C1C1E"
font = "sans serif"

[client]
showSidebarNavigation = false

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
