[theme]
primaryColor = "#0071E3"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F7"
textColor = "#1D1D1F"
font = "sans serif"

[client]
showSidebarNavigation = false

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
