[theme]
primaryColor = "#F0EEE9"
backgroundColor = "#121212"
secondaryBackgroundColor = "#1C1C1E"
textColor = "#F0EEE9"
font = "sans serif"

[client]
showSidebarNavigation = false

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
