[theme]
primaryColor = "#F0EEE9"
backgroundColor = "#000000"
secondaryBackgroundColor = "#1C1C1E"
textColor = "#F0EEE9"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
